#!/bin/bash

#check to make sure they only entered one argument
if [ "$#" -ne 2 ]; then
	echo "Error!"
	echo "Usage: ./html_scrape <job> <location>"
	exit 1
fi

# job search query
q_job="$1"

# job search location
q_location="$2"

# Set the location param query val
case "$q_location" in

	"Columbus")
		q_location_num=1
		;;

	"Lima")
		q_location_num=2
		;;

	"Mansfield")
		q_location_num=3
		;;

	"Marion")
		q_location_num=4
		;;

	"Newark")
		q_location_num=5
		;;

	"Wooster")
		q_location_num=6
		;;

	"Delaware")
		q_location_num=8
		;;

	"Springfield")
		q_location_num=9
		;;

	"Piketon")
		q_location_num=10
		;;

	"Dayton")
		q_location_num=11
		;;

	*)
		echo "You did not enter a valid location in Ohio. Please try again."
		exit 1
		;;
	esac

echo "Searching for $q_job type jobs in $q_location..."

curl -L -s --max-time 60 --data "query=$q_job&591=$q_location_num" https://www.jobsatosu.com/postings/search/ | sed -e '/^$/d' -e 's/^ *//' -e's/[[:space:]]*//' > "job_listings.html"

counter=0
open_div=0
close_div=0

#read through each line of the raw html
while read line
do
	#see if we found job posting class in HTML
	title=$(echo "$line" | grep 'data-posting-title')
	if [ ! -z "$title" ]; then
		counter=$[$counter+1]
		open_div=$[$open_div+1]
		echo -ne "Found $counter postings\r"

		#echo the first line and then go to next loop iteration
		echo "$line" >> output.html
		continue
	fi

	# avoid all the other div tags until we hit the target class title 'data-posting-title'
	if [ $open_div -eq 0 ] && [ $close_div -eq 0 ]; then
		continue
	fi

	# we are in the posting block so echo to output.html
	echo "$line" >> output.html

	# grep for either an opening tag or a closing one
	opening=$(echo "$line" | grep -o '<div')
	closing=$(echo "$line" | grep -o '</div>')

	# if we don't have a closing or opening tag then skip to next loop to save
	#memory 
	if [ -z "$opening" ] && [ -z "$closing" ]; then
		continue
	fi

	# we found an opening div tag so increment the counter
	if [ ! -z "$opening" ]; then
		open_div=$[$open_div+1]
		continue
	fi
	
	# we found a closing div tag so increment the counter
	if [ ! -z "$closing" ]; then
		close_div=$[$close_div+1]
	fi

	# if our two counters are not 0 and they are equal then we hit the end of a posting block
	if [ $open_div -eq $close_div ] && [ $open_div -ne 0 ] && [ $close_div -ne 0 ]; then
		open_div=0
		close_div=0
		echo "END POSTING" >> output.html
	fi
done < "job_listings.html"

# print out how many listings we found
echo "Found a total of $counter postings."

# get rid of the raw GET response HTML
# rm "job_listings.html"

# we didn't find any listings so exit
if [ $counter -eq 0 ]; then
	exit 1
fi


# set up a counter
count=1

# grab each line where it doesn't start with a tag character and grab that data
while read line
do
	is_tag=$(echo "$line" | grep -o "^<" )

	if [ -z "$is_tag" ]; then

		# check counter to see what the line is going to print
		case "$count" in

			"1")
			echo "Work Title: $line " >> jobs.txt
			;;

			"2")
			echo "Department: $line " >> jobs.txt
			;;
			
			"3")
			echo "Application Deadline: $line " >> jobs.txt
			;;
			
			"4")
			echo "Job Opening Number: $line " >> jobs.txt
			;;
			
			"5")
			echo "Target Salary: $line " >> jobs.txt
			;;

			"6")
			echo "Description: $line " >> jobs.txt
			;;

			"7")
			echo "--------------------------------------------------------------------------" >> jobs.txt
			# this is the END POSTING line. reset the counter
			count=0
			;;

			*)
			;;
			esac

		echo "$line"
		count=$[$count+1]

	fi
done < "output.html"

# remove the output.html
rm "output.html"
# rm "jobs.txt"

